sender should have the option to decide
intarchboard/draft-path-signals-collaboration pull request #100
Opened 2022-10-13 17:22 UTC by mirjak

fixes #89

Is that sufficient?

2022-10-13 18:19 UTC, tfpauly requested changes

2022-10-13 18:19 UTC, tfpauly commented on draft-iab-path-signals-collaboration.md
> +to a specific entities or set of entities.
```suggestion
The sender needs to decide that it is willing to send information to a specific entity or
set of entities.
```

2022-10-13 18:19 UTC, tfpauly commented on draft-iab-path-signals-collaboration.md
> +request should have the option to agree or deny to receiving the information. It
```suggestion
request needs to decide that it is willing to receive the information. It
```

2022-10-14 06:47 UTC, mirjak commented
@tfpauly your wording is find but that doesn't capture the aspect that the protocol design actually needs to have a option to configure. I guess that was too subtle in my sentence as well. Should we add a separate sentence maybe?

2022-10-14 16:47 UTC, mirjak commented
Yes, this beyond is beyond what's raised in the issue. It's not about the application is doing but what to consider in protocol design. I was think about quic and the spin bit and basically saying that there should be an option in the proposal to disable it.

2022-10-14 18:48 UTC, tfpauly commented
Ah, I see — a protocol/spec-level option, not a runtime or software configuration option. That's not super clear...

2022-10-14 19:09 UTC, mirjak commented
Isn't the whole document about protocol design recommendations...? ;-)

How can we make that more clear?

2022-10-19 14:25 UTC, jariarkko approved these changes
I think we are good to go. I will apply this PR later today if I don't hear otherwise.

2022-10-19 14:29 UTC, tfpauly approved these changes

2022-10-19 18:11 UTC, jariarkko approved these changes

2022-10-19 18:12 UTC, jariarkko commented
Based on chat discussion I'm applying this as originally suggested.

2022-10-19 18:12 UTC, merged